AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - log/**/*

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Bundler/OrderedGems:
  Enabled: false

Lint/Void:
  Exclude:
    - spec/**/*.rb
